
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

//for (int i = 0; i < Employee.listOfEmployee.size()  ;i++){
//            Employee temporaryEmployee = Employee.listOfEmployee.get(i);
//            for(int j = 0; j< temporaryEmployee.listOfMedicalActivities1.size() ; j++){
//                System.out.println("Name: " + temporaryEmployee.getSurname() +
//                        " Medical Activity: " + temporaryEmployee.listOfMedicalActivities1.get(j).getMedicalActivities());
//      }}  

/**
 *
 * @author Admin
 */
public class MainPanel extends javax.swing.JFrame {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton2.setText("Add Patient");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add Graphic For Employee");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("LogIn");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("About the clinic");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Patient Database");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("MakeAnAppointment");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 173, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
         new AddingPatient().setVisible(true);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        new EmployeeSchedule().setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        new LogIn().setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new AboutTheClinic().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         new PatientDatabase().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         new MakeAnApointment1().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        //SaveToFile.saveAppointment(Appointment.appointmentList);
        //SaveToFile.saveGraphic(Graphic.graphicList);
        //SaveToFile.savePatient(Patient.listOfPatients);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //SaveToFile.readAppointment(Appointment.appointmentList);
        //SaveToFile.readGraphic(Graphic.graphicList);
        //SaveToFile.readPatient(Patient.listOfPatients);
    }//GEN-LAST:event_formWindowOpened

    /**
     *
     * @param args
     */
    
    
    public static void main(String args[]) 
    {
       
        MedicalActivities medicalActivities1 = new MedicalActivities();
        MedicalActivities medicalActivities2 = new MedicalActivities();
        MedicalActivities medicalActivities3 = new MedicalActivities();
        MedicalActivities medicalActivities4 = new MedicalActivities();
        MedicalActivities medicalActivities5 = new MedicalActivities();
        MedicalActivities medicalActivities6 = new MedicalActivities();
        
        medicalActivities1.setMedicalActivities("Morphology");
        medicalActivities2.setMedicalActivities("UrineTest");
        medicalActivities3.setMedicalActivities("ThyroidExamination");
        medicalActivities4.setMedicalActivities("EKG");
        medicalActivities5.setMedicalActivities("USG");
        medicalActivities6.setMedicalActivities("LiverTests");

       
        MedicalActivities.listOfMedicalActivities.add(medicalActivities1);
        MedicalActivities.listOfMedicalActivities.add(medicalActivities2);
        MedicalActivities.listOfMedicalActivities.add(medicalActivities3);
        MedicalActivities.listOfMedicalActivities.add(medicalActivities4);
        MedicalActivities.listOfMedicalActivities.add(medicalActivities5);
        MedicalActivities.listOfMedicalActivities.add(medicalActivities6);
        
        Employee e1 = new Employee();
        e1.setName("Edyta");
        e1.setSurname("Karpowicz");
        e1.setYearOfStartingWork(1999);
        e1.listOfMedicalActivities1.add(MedicalActivities.listOfMedicalActivities.get(0));
        e1.listOfMedicalActivities1.add(MedicalActivities.listOfMedicalActivities.get(1));
        e1.listOfMedicalActivities1.add(MedicalActivities.listOfMedicalActivities.get(2));
        
        Employee e2 = new Employee();
        e2.setName("Magda");
        e2.setSurname("Karpińska");
        e2.setYearOfStartingWork(1998);
        e2.listOfMedicalActivities1.add(MedicalActivities.listOfMedicalActivities.get(1));
        e2.listOfMedicalActivities1.add(MedicalActivities.listOfMedicalActivities.get(2));
        e2.listOfMedicalActivities1.add(MedicalActivities.listOfMedicalActivities.get(3));
        
        Employee e3 = new Employee();
        e3.setName("Jan");
        e3.setSurname("Kowalski");
        e3.setYearOfStartingWork(2000);
        e3.listOfMedicalActivities1.add(MedicalActivities.listOfMedicalActivities.get(1));
        e3.listOfMedicalActivities1.add(MedicalActivities.listOfMedicalActivities.get(2));
        e3.listOfMedicalActivities1.add(MedicalActivities.listOfMedicalActivities.get(4));
        
        Employee e4 = new Employee();
        e4.setName("Tomek");
        e4.setSurname("Tomański");
        e4.setYearOfStartingWork(1995);
        e4.listOfMedicalActivities1.add(MedicalActivities.listOfMedicalActivities.get(3));
        e4.listOfMedicalActivities1.add(MedicalActivities.listOfMedicalActivities.get(4));
        e4.listOfMedicalActivities1.add(MedicalActivities.listOfMedicalActivities.get(5));
        
        Employee e5 = new Employee();
        e5.setName("Bartłomiej");
        e5.setSurname("Stefański");
        e5.setYearOfStartingWork(2002);
        e5.listOfMedicalActivities1.add(MedicalActivities.listOfMedicalActivities.get(1));
        e5.listOfMedicalActivities1.add(MedicalActivities.listOfMedicalActivities.get(4));
        e5.listOfMedicalActivities1.add(MedicalActivities.listOfMedicalActivities.get(5));
        
        Employee.listOfEmployee.add(e1);
        Employee.listOfEmployee.add(e2);
        Employee.listOfEmployee.add(e3);
        Employee.listOfEmployee.add(e4);
        Employee.listOfEmployee.add(e5);
        
        
        
         for(int i = 1 ; i <=10; i++)
         {
            Cabinet.listOfCabinets.add(new Cabinet(i+""));
         }
         
         
         
         Patient p1 = new Patient("Daniel","Kowalski","99100908989","06-11-1999","Wierzba 45",456345876,"danielk@o2.pl");
         Patient p2 = new Patient("Edyta","Kowalska","99890908989","09-01-1989","Małochwiej 105",657385876,"edytkakp@o2.pl");
         Patient p3 = new Patient("Bartłomiej","Jakow","67700808989","12-11-1996","Chomescika 55",566378896,"bartekj@o2.pl");
         Patient p4 = new Patient("Michał","Krakowski","98106908783","06-08-1967","Włocławe 25",896045806,"michalk@o2.pl");
         Patient p5 = new Patient("Stefan","Jordan","89234908679","24-10-1976","Krasne 23",675345824,"stefanj@o2.pl");

       
        p1.autorizedPeopleToHealthInformationList.add("Kacper Nowak");
        p1.autorizedPeopleToHealthInformationList.add("Filip Kowalski");
        p1.autorizedPeopleToHealthInformationList.add("Mateusz Wiśniewski");
        p1.autorizedPeopleToHealthInformationList.add("Kamil Wójcik ");
        p1.autorizedPeopleToMedicalRecorsList.add("Kacper Nowak");
        p1.autorizedPeopleToMedicalRecorsList.add("Filip Kowalski");
        p1.autorizedPeopleToMedicalRecorsList.add("Mateusz Wiśniewski");
        p1.autorizedPeopleToMedicalRecorsList.add("Kamil Wójcik ");
        
        p2.autorizedPeopleToHealthInformationList.add("Norbert Kowalski");
        p2.autorizedPeopleToHealthInformationList.add("Krzysztof Kowalski");
        p2.autorizedPeopleToHealthInformationList.add("Małgorzata Kowalska");
        p2.autorizedPeopleToHealthInformationList.add("Kamil Wójcik ");
        p2.autorizedPeopleToMedicalRecorsList.add("Norbert Kowalski");
        p2.autorizedPeopleToMedicalRecorsList.add("Krzysztof Kowalski");
        p2.autorizedPeopleToMedicalRecorsList.add("Małgorzata Kowalska");
        p2.autorizedPeopleToMedicalRecorsList.add("Kamil Małopolski ");
        
        p3.autorizedPeopleToHealthInformationList.add("Artur Jakow");
        p3.autorizedPeopleToHealthInformationList.add("Krzysztof Jakow");
        p3.autorizedPeopleToHealthInformationList.add("Barbara Jakow");
        p3.autorizedPeopleToHealthInformationList.add("Rafał Wójcik ");
        p3.autorizedPeopleToMedicalRecorsList.add("Artur Jakow");
        p3.autorizedPeopleToMedicalRecorsList.add("Krzysztof Jakow");
        p3.autorizedPeopleToMedicalRecorsList.add("Barbara Jakow");
        p3.autorizedPeopleToMedicalRecorsList.add("Kamil Stefan");
        
        p4.autorizedPeopleToHealthInformationList.add("Artur Krakowski");
        p4.autorizedPeopleToHealthInformationList.add("Krzysztof Krakowski");
        p4.autorizedPeopleToHealthInformationList.add("Barbara Krakowski");
        p4.autorizedPeopleToHealthInformationList.add("Paweł Wójcik ");
        p4.autorizedPeopleToMedicalRecorsList.add("Artur Krakowski");
        p4.autorizedPeopleToMedicalRecorsList.add("Krzysztof Krakowski");
        p4.autorizedPeopleToMedicalRecorsList.add("Barbara Krakowski");
        p4.autorizedPeopleToMedicalRecorsList.add("Norbert Wójt");
        
        p5.autorizedPeopleToHealthInformationList.add("Anna Jordan");
        p5.autorizedPeopleToHealthInformationList.add("Krzysztof Jordan");
        p5.autorizedPeopleToHealthInformationList.add("Paweł Jordan");
        p5.autorizedPeopleToHealthInformationList.add("Paweł Marek ");
        p5.autorizedPeopleToMedicalRecorsList.add("Anna Jordan");
        p5.autorizedPeopleToMedicalRecorsList.add("Stefan Krakowski");
        p5.autorizedPeopleToMedicalRecorsList.add("Paweł Jordan");
        p5.autorizedPeopleToMedicalRecorsList.add("Norbert Bebowski");
        
        Patient.listOfPatients.add(p1);
        Patient.listOfPatients.add(p2);
        Patient.listOfPatients.add(p3);
        Patient.listOfPatients.add(p4);
        Patient.listOfPatients.add(p5);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables
}
